version: '3.8'

services:
  # Movies API
  api:
    image: doconnor/movies-api:1.0
    container_name: movies-api
    ports:
      - '9000:9000'
    environment:
      MONGODB_URI: "mongodb://mongo:27017"
      REDIS_URI: "redis://redis:6379"
      ENABLE_WRITING_HANDLERS: "false"
    depends_on:
      - mongo
      - redis

  # MongoDB
  mongo:
    image: mongo:8.0-rc
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: "admin"
      MONGO_INITDB_ROOT_PASSWORD: "password"
    ports:
      - '27017:27017'  
    volumes:
      - mongo_data:/data/db

  # Redis
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - '6379:6379'

  # Mongo Express
  mongo-express:
    image: mongo-express:1.0-20-alpine3.19
    container_name: mongo-express
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: "admin"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "password"
      ME_CONFIG_MONGODB_URL: "mongodb://admin:password@mongo:27017"
    depends_on:
      - mongo

volumes:
  mongo_data:
